#!/usr/bin/env python3
"""DragonMax 4.8 presentation upgrade: animated Home + routed controls."""
import repo_release as _base

_VERSION = '4.8.0'
_base._RELEASE_VERSION = _VERSION
_base._r.VERSION = _VERSION
_base._r.REPO = _base._r.REPO.replace('4.7.0', _VERSION)
_base._r.ADDON = _base._r.ADDON.replace('4.7.0', _VERSION)
_base._r.DEFAULT = _base._r.DEFAULT.replace('4.7.0', _VERSION)

_base._DRAGONMAX_MAINMENU = '''<?xml version="1.0" encoding="UTF-8"?>
<shortcuts>
 <shortcut><label>Dragon Portal</label><label2>DragonMax</label2><defaultID>dragonportal</defaultID><icon>special://home/artwork/realm_crests/dragon_order_crest.png</icon><thumb>special://home/artwork/portal_graphics/dragon_order_portal.png</thumb><action>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=open&amp;target=portal)</action></shortcut>
 <shortcut><label>Continue Watching</label><label2>DragonMax</label2><defaultID>continuewatching</defaultID><icon>special://skin/extras/icons/playlist.png</icon><thumb>special://home/artwork/hero_banners/dragon_order/dragon_order_hero_01.png</thumb><action>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=open&amp;target=continue)</action></shortcut>
 <shortcut><label>Movies</label><label2>DragonMax</label2><defaultID>movies</defaultID><icon>special://skin/extras/icons/film.png</icon><thumb>special://home/artwork/hero_banners/crimson_court/crimson_court_hero_01.png</thumb><action>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=open&amp;target=movies)</action></shortcut>
 <shortcut><label>TV Shows</label><label2>DragonMax</label2><defaultID>tvshows</defaultID><icon>special://skin/extras/icons/tv.png</icon><thumb>special://home/artwork/hero_banners/arcane_dominion/arcane_dominion_hero_01.png</thumb><action>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=open&amp;target=tv)</action></shortcut>
 <shortcut><label>Anime Universe</label><label2>DragonMax Realm</label2><defaultID>animeuniverse</defaultID><icon>special://home/artwork/realm_crests/arcane_dominion_crest.png</icon><action>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=set_realm&amp;realm=arcane_dominion)</action></shortcut>
 <shortcut><label>Martial Arts</label><label2>DragonMax Realm</label2><defaultID>martialarts</defaultID><icon>special://home/artwork/realm_crests/temple_guardians_crest.png</icon><action>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=set_realm&amp;realm=temple_guardians)</action></shortcut>
 <shortcut><label>Champion Guild</label><label2>DragonMax Realm</label2><defaultID>championguild</defaultID><icon>special://home/artwork/realm_crests/champion_guild_crest.png</icon><action>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=set_realm&amp;realm=champion_guild)</action></shortcut>
 <shortcut><label>Office Consortium</label><label2>DragonMax Realm</label2><defaultID>officeconsortium</defaultID><icon>special://home/artwork/realm_crests/office_consortium_crest.png</icon><action>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=set_realm&amp;realm=office_consortium)</action></shortcut>
 <shortcut><label>Settings</label><label2>DragonMax</label2><defaultID>settings</defaultID><icon>special://skin/extras/icons/settings.png</icon><action>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=open&amp;target=settings)</action></shortcut>
</shortcuts>'''

_base._DRAGONMAX_HOME_XML = '''<?xml version="1.0" encoding="UTF-8"?>
<window id="0">
 <defaultcontrol always="true">5001</defaultcontrol>
 <onload condition="String.IsEmpty(Skin.String(DragonMaxRealm))">Skin.SetString(DragonMaxRealm,dragon_order)</onload>
 <onload condition="String.IsEmpty(Skin.String(DragonMaxRealmName))">Skin.SetString(DragonMaxRealmName,Dragon Order)</onload>
 <controls>
  <control type="multiimage"><left>0</left><top>0</top><width>1920</width><height>1080</height><imagepath>special://home/artwork/wallpapers/dragon_order/</imagepath><timeperimage>9000</timeperimage><fadetime>1400</fadetime><randomize>true</randomize><visible>String.IsEqual(Skin.String(DragonMaxRealm),dragon_order)</visible><animation effect="fade" start="0" end="100" time="450">VisibleChange</animation></control>
  <control type="multiimage"><left>0</left><top>0</top><width>1920</width><height>1080</height><imagepath>special://home/artwork/wallpapers/arcane_dominion/</imagepath><timeperimage>9000</timeperimage><fadetime>1400</fadetime><randomize>true</randomize><visible>String.IsEqual(Skin.String(DragonMaxRealm),arcane_dominion)</visible><animation effect="fade" start="0" end="100" time="450">VisibleChange</animation></control>
  <control type="multiimage"><left>0</left><top>0</top><width>1920</width><height>1080</height><imagepath>special://home/artwork/wallpapers/crimson_court/</imagepath><timeperimage>9000</timeperimage><fadetime>1400</fadetime><randomize>true</randomize><visible>String.IsEqual(Skin.String(DragonMaxRealm),crimson_court)</visible><animation effect="fade" start="0" end="100" time="450">VisibleChange</animation></control>
  <control type="multiimage"><left>0</left><top>0</top><width>1920</width><height>1080</height><imagepath>special://home/artwork/wallpapers/temple_guardians/</imagepath><timeperimage>9000</timeperimage><fadetime>1400</fadetime><randomize>true</randomize><visible>String.IsEqual(Skin.String(DragonMaxRealm),temple_guardians)</visible><animation effect="fade" start="0" end="100" time="450">VisibleChange</animation></control>
  <control type="multiimage"><left>0</left><top>0</top><width>1920</width><height>1080</height><imagepath>special://home/artwork/wallpapers/champion_guild/</imagepath><timeperimage>9000</timeperimage><fadetime>1400</fadetime><randomize>true</randomize><visible>String.IsEqual(Skin.String(DragonMaxRealm),champion_guild)</visible><animation effect="fade" start="0" end="100" time="450">VisibleChange</animation></control>
  <control type="multiimage"><left>0</left><top>0</top><width>1920</width><height>1080</height><imagepath>special://home/artwork/wallpapers/office_consortium/</imagepath><timeperimage>9000</timeperimage><fadetime>1400</fadetime><randomize>true</randomize><visible>String.IsEqual(Skin.String(DragonMaxRealm),office_consortium)</visible><animation effect="fade" start="0" end="100" time="450">VisibleChange</animation></control>
  <control type="image"><left>0</left><top>0</top><width>1920</width><height>1080</height><texture colordiffuse="A8000000">common/white.png</texture></control>

  <control type="group"><animation effect="fade" start="0" end="100" time="450">WindowOpen</animation><animation effect="slide" start="0,-35" end="0,0" time="450" tween="quadratic" easing="out">WindowOpen</animation>
   <control type="image"><left>70</left><top>38</top><width>118</width><height>118</height><aspectratio>keep</aspectratio><texture>special://home/artwork/realm_crests/dragon_order_crest.png</texture><animation effect="zoom" start="94" end="100" time="500" center="auto">WindowOpen</animation></control>
   <control type="label"><left>210</left><top>42</top><width>720</width><height>55</height><font>font45</font><label>DRAGONMAX</label><textcolor>FFFFFFFF</textcolor></control>
   <control type="label"><left>213</left><top>98</top><width>700</width><height>38</height><font>font20</font><label>$INFO[Skin.String(DragonMaxRealmName)]</label><textcolor>FFFFA62B</textcolor></control>
  </control>

  <control type="group"><left>70</left><top>175</top><animation effect="fade" start="0" end="100" time="650" delay="120">WindowOpen</animation><animation effect="slide" start="-55,0" end="0,0" time="650" tween="quadratic" easing="out" delay="120">WindowOpen</animation>
   <control type="multiimage"><left>0</left><top>0</top><width>1160</width><height>430</height><aspectratio>scale</aspectratio><imagepath>special://home/artwork/hero_banners/dragon_order/</imagepath><timeperimage>7000</timeperimage><fadetime>900</fadetime><randomize>true</randomize></control>
   <control type="image"><left>0</left><top>0</top><width>1160</width><height>430</height><texture colordiffuse="50000000">common/white.png</texture></control>
   <control type="label"><left>42</left><top>285</top><width>900</width><height>54</height><font>font35</font><label>ENTER THE DRAGON REALMS</label><textcolor>FFFFFFFF</textcolor></control>
   <control type="label"><left>44</left><top>342</top><width>950</width><height>40</height><font>font20</font><label>Movies • Television • Anime • Martial Arts • Champions • Office</label><textcolor>FFDDDDDD</textcolor></control>
  </control>

  <control type="group"><left>1280</left><top>185</top><animation effect="fade" start="0" end="100" time="650" delay="250">WindowOpen</animation>
   <control type="label"><left>0</left><top>0</top><width>520</width><height>45</height><font>font30</font><label>DRAGON PORTAL</label><textcolor>FFFFA62B</textcolor></control>
   <control type="image"><left>20</left><top>58</top><width>430</width><height>245</height><aspectratio>keep</aspectratio><texture>special://home/artwork/portal_graphics/dragon_order_portal.png</texture></control>
   <control type="label"><left>0</left><top>318</top><width>510</width><height>88</height><font>font18</font><label>Switch realms • Performance • Weather • Maintenance • Repair</label><wrapmultiline>true</wrapmultiline><textcolor>FFCCCCCC</textcolor></control>
  </control>

  <control type="group"><left>70</left><top>635</top><animation effect="fade" start="0" end="100" time="450" delay="350">WindowOpen</animation>
   <control type="button" id="5001"><left>0</left><top>0</top><width>195</width><height>64</height><font>font20</font><label>DRAGON PORTAL</label><texturefocus colordiffuse="FFFFA62B">common/white.png</texturefocus><texturenofocus colordiffuse="44111111">common/white.png</texturenofocus><textcolor>FFFFFFFF</textcolor><focusedcolor>FF111111</focusedcolor><onclick>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=open&amp;target=portal)</onclick><onright>5002</onright><onleft>5009</onleft><ondown>6100</ondown><animation effect="zoom" start="100" end="108" time="120" center="auto" reversible="true">Focus</animation></control>
   <control type="button" id="5002"><left>205</left><top>0</top><width>178</width><height>64</height><font>font20</font><label>CONTINUE</label><texturefocus colordiffuse="FFFFA62B">common/white.png</texturefocus><texturenofocus colordiffuse="44111111">common/white.png</texturenofocus><textcolor>FFFFFFFF</textcolor><focusedcolor>FF111111</focusedcolor><onclick>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=open&amp;target=continue)</onclick><onright>5003</onright><onleft>5001</onleft><ondown>6100</ondown><animation effect="zoom" start="100" end="108" time="120" center="auto" reversible="true">Focus</animation></control>
   <control type="button" id="5003"><left>393</left><top>0</top><width>150</width><height>64</height><font>font20</font><label>MOVIES</label><texturefocus colordiffuse="FFFFA62B">common/white.png</texturefocus><texturenofocus colordiffuse="44111111">common/white.png</texturenofocus><textcolor>FFFFFFFF</textcolor><focusedcolor>FF111111</focusedcolor><onclick>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=open&amp;target=movies)</onclick><onright>5004</onright><onleft>5002</onleft><ondown>6100</ondown><animation effect="zoom" start="100" end="108" time="120" center="auto" reversible="true">Focus</animation></control>
   <control type="button" id="5004"><left>553</left><top>0</top><width>150</width><height>64</height><font>font20</font><label>TV SHOWS</label><texturefocus colordiffuse="FFFFA62B">common/white.png</texturefocus><texturenofocus colordiffuse="44111111">common/white.png</texturenofocus><textcolor>FFFFFFFF</textcolor><focusedcolor>FF111111</focusedcolor><onclick>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=open&amp;target=tv)</onclick><onright>5005</onright><onleft>5003</onleft><ondown>6100</ondown><animation effect="zoom" start="100" end="108" time="120" center="auto" reversible="true">Focus</animation></control>
   <control type="button" id="5005"><left>713</left><top>0</top><width>150</width><height>64</height><font>font20</font><label>ANIME</label><texturefocus colordiffuse="FFFFA62B">common/white.png</texturefocus><texturenofocus colordiffuse="44111111">common/white.png</texturenofocus><textcolor>FFFFFFFF</textcolor><focusedcolor>FF111111</focusedcolor><onclick>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=set_realm&amp;realm=arcane_dominion)</onclick><onright>5006</onright><onleft>5004</onleft><ondown>6100</ondown><animation effect="zoom" start="100" end="108" time="120" center="auto" reversible="true">Focus</animation></control>
   <control type="button" id="5006"><left>873</left><top>0</top><width>185</width><height>64</height><font>font20</font><label>MARTIAL ARTS</label><texturefocus colordiffuse="FFFFA62B">common/white.png</texturefocus><texturenofocus colordiffuse="44111111">common/white.png</texturenofocus><textcolor>FFFFFFFF</textcolor><focusedcolor>FF111111</focusedcolor><onclick>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=set_realm&amp;realm=temple_guardians)</onclick><onright>5007</onright><onleft>5005</onleft><ondown>6100</ondown><animation effect="zoom" start="100" end="108" time="120" center="auto" reversible="true">Focus</animation></control>
   <control type="button" id="5007"><left>1068</left><top>0</top><width>175</width><height>64</height><font>font20</font><label>CHAMPIONS</label><texturefocus colordiffuse="FFFFA62B">common/white.png</texturefocus><texturenofocus colordiffuse="44111111">common/white.png</texturenofocus><textcolor>FFFFFFFF</textcolor><focusedcolor>FF111111</focusedcolor><onclick>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=set_realm&amp;realm=champion_guild)</onclick><onright>5008</onright><onleft>5006</onleft><ondown>6100</ondown><animation effect="zoom" start="100" end="108" time="120" center="auto" reversible="true">Focus</animation></control>
   <control type="button" id="5008"><left>1253</left><top>0</top><width>160</width><height>64</height><font>font20</font><label>OFFICE</label><texturefocus colordiffuse="FFFFA62B">common/white.png</texturefocus><texturenofocus colordiffuse="44111111">common/white.png</texturenofocus><textcolor>FFFFFFFF</textcolor><focusedcolor>FF111111</focusedcolor><onclick>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=set_realm&amp;realm=office_consortium)</onclick><onright>5009</onright><onleft>5007</onleft><ondown>6100</ondown><animation effect="zoom" start="100" end="108" time="120" center="auto" reversible="true">Focus</animation></control>
   <control type="button" id="5009"><left>1423</left><top>0</top><width>150</width><height>64</height><font>font20</font><label>SETTINGS</label><texturefocus colordiffuse="FFFFA62B">common/white.png</texturefocus><texturenofocus colordiffuse="44111111">common/white.png</texturenofocus><textcolor>FFFFFFFF</textcolor><focusedcolor>FF111111</focusedcolor><onclick>RunPlugin(plugin://plugin.program.dragonmaxportal/?action=open&amp;target=settings)</onclick><onright>5001</onright><onleft>5008</onleft><ondown>6100</ondown><animation effect="zoom" start="100" end="108" time="120" center="auto" reversible="true">Focus</animation></control>
  </control>

  <control type="label"><left>70</left><top>735</top><width>650</width><height>42</height><font>font25</font><label>TRENDING MOVIES</label><textcolor>FFFFFFFF</textcolor><animation effect="fade" start="0" end="100" time="400" delay="450">WindowOpen</animation></control>
  <control type="fixedlist" id="6100"><left>70</left><top>785</top><width>1780</width><height>245</height><orientation>horizontal</orientation><focusposition>0</focusposition><onup>5001</onup><animation effect="fade" start="0" end="100" time="500" delay="500">WindowOpen</animation>
   <itemlayout width="190" height="240"><control type="image"><left>8</left><top>8</top><width>168</width><height>215</height><aspectratio>scale</aspectratio><texture>$INFO[ListItem.Art(poster)]</texture></control></itemlayout>
   <focusedlayout width="205" height="240"><control type="image"><left>6</left><top>0</top><width>186</width><height>230</height><aspectratio>scale</aspectratio><texture>$INFO[ListItem.Art(poster)]</texture><bordertexture border="5">common/white.png</bordertexture><bordersize>5</bordersize><animation effect="zoom" start="96" end="104" time="120" center="auto">Focus</animation></control></focusedlayout>
   <content target="videos">plugin://plugin.video.themoviedb.helper/?info=popular&amp;type=movie&amp;widget=True</content>
  </control>
 </controls>
</window>'''

# The base tracer reads these globals dynamically when build_v12 defines its functions.
from repo_release import *
DEFAULT = _base._r.DEFAULT
